# NOTE: use $$ to escape $ in docker compose yaml

# The config below was obtained from: https://learn.netdata.cloud/docs/netdata-agent/installation/docker#recommended-way

services:
  netdata:
    image: netdata/netdata:latest
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    # ports: # No need to expose ports when using a reverse proxy like NPM as a sibling compose service
    #   - 19999:19999 # web dashboard
    volumes:
      - netdata_data:/etc/netdata
      - netdata_data:/var/lib/netdata
      - netdata_data:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  netdata_data: